### PR TITLE
Example structure.

### PR DESCRIPTION
**Pull request by timsifive**
This combines most of what we talked about in this week's meeting.
Definitely need more details about Physical Memory (is that even a task
group), and caches.

### CODE REVIEW

**Comment by allenjbaum** [comment]
Looking through your example:
\item triple of VALUE0, MASK0
That's a tuple, not a triple

**Comment by timsifive** [comment]
Thanks. There are a few typos in this file. However, this file does not include "\item" anywhere, which makes me wonder if you were looking at this example.md, or at something we previously wrote in LaTeX.

**Comment by allenjbaum** [comment]
I looked at the link, couldn’t find pre-built .pdf, looked at the changes, and that’s what popped up. It may have been example.md, I’ll go back and look.

-Allen

**Comment by timsifive** [comment]
Merging, to make it easier to access these examples. Let's get all our examples here so they're in one place.

**Pull request merged**
