### PR TITLE
Convert the project to the RISC-V docs-template.

### PR DESCRIPTION
**Pull request by jjscheel**
Merging updates to adopt the RISC-V document template (#68)

Signed-off-by: Jeff Scheel <jeff@riscv.org>

### CODE REVIEW

**Comment by timsifive** [comment]
Can you add the `git submodule` explanation you put into #68 to the README.md?

**Comment by cetola** [comment]
@jjscheel If you remove the "-r asciidoctor-diagram" flag from the Makefile edits in this commit, the PR will build just fine. 

This brings up the larger question. Do you think it's better to keep the builds consistent across repos, or allow repos to simplify their builds if applicable? This repo is a good example of this idea.

I don't have a strong opinion but if we allow folks to keep their builds as simple as possible it does save us GitHub action cycles (which if free, are limited for our Org). The tradeoff is that each spec's build script will be unique rather than mirroring the docs-spec-template.

**Comment by jjscheel** [comment]
@cetola, my personal preference is to only enable the features/functions one needs.  So, your suggestion might be better than re-working the Git Actions.

First thing tomorrow, I'll update the Makefile and either submit a new PR or try and add it to this one.

Sound, ok, @timsifive?

**Comment by changab** [comment]
Not sure if org has this or not? Could we have a label for PR that triggers Git action to convert the asciidoc to PDF, with the repo-specific asciidoc attributes and build options? Then merge the PDF to repo automatically. Thus we don't have to set up the local environment for asciidoc-pdf and run it locally.

**Comment by jjscheel** [comment]
Will cleanup and re-submit.

**Comment by jjscheel** [comment]
@changab, FWIW, I think your question is a fair one.  The build actions were added by @timsifive very recently (just before my submission), not by my proposed patch.  As such, I'd suggest we move your discussion to a new issue.  

In addition, I'd note that the [docs-dev-guide](https://github.com/riscv/docs-dev-guide) project does what you suggest.

**Pull request closed without merging**
